### ISSUE TITLE
https://now-ui-dashboard-pro-laravel.creative-tim.com/lock has issues when one is logged in

### ISSUE THREAD

**Issue by jcherrabi** [creativetimofficial/ct-now-ui-dashboard-pro-laravel#1]
if you go to the lock page while logged the page breaks.
https://now-ui-dashboard-pro-laravel.creative-tim.com/lock

also after i added the missing activeNav variable on top of the lock.blade.php page, i was able to to get to it but it was useless as all the menus were accessible...

can you please fix it to where it would hide everything and show the big background image just like when you get to it from the front page?

thanks

**Comment by teamupdivision** [comment]
Hello @jcherrabi!
Thanks for using our products.
We'll follow up with a fix in short time.

All the best

**Comment by teamupdivision** [comment]
Hello again,
We fixed the issue reported.
We also updated the code to the latest Laravel template, you can download it from the download section in the Creative Tim website.
Check it out.

Thank you
