### ISSUE TITLE
Now UI Broke input-group-append code

### ISSUE THREAD

**Issue by jcherrabi** [creativetimofficial/ct-now-ui-dashboard-pro-laravel#2]
# Prerequisites
Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Append a eye password revealer to the right side of the password input box in the login page!

# Current Behavior
the eye password revealer cuts off from the input box and no longer part of the input 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
 in the login.blade.php
2. step 2
locate the password input box and add the following code after it:
`                                <div class="input-group-append">
                                        <span class="input-group-text">
                                            <a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                                        </span>
                                </div>`

or a complete code with prepend and append the same icon, which will cause the right to look broken off:

`<div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <i class="now-ui-icons users_single-02"></i>
                                    </div>
                                </div>
                                <input type="text" class="form-control" placeholder="With Nucleo Icons">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <i class="now-ui-icons users_single-02"></i>
                                    </div>
                                </div>
                            </div>`

3. you get it...
a detached eye icon from the input box

Code taken from the docs: https://www.creative-tim.com/live/now-ui-dashboard-pro-laravel/?start-page=/docs/getting-started/laravel-setup.html

also please update the docs and add an example to show a prepend and append icons to an input box

**Comment by teamupdivision** [comment]
Hello, thank you for using our products!

Can you please tell us where did you take this code from
`<div class="input-group-append"> <span class="input-group-text"> <a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a> </span> </div>`

When you say to remove the template, what template are you referring to? please send a link.

Thank you

**Comment by jcherrabi** [comment]
> When you say to remove the template, what template are you referring to? please send a link.

I didn't write that, it was already written in the comments by GitHub I guess, anyway I removed the above confusing sentence from my comments.

as for the code please open the log.blade.php and add the above code and you will see the issue... the prepend works on its own but as soon as you try to add an append behavior it breaks.
![Annotation 2020-03-25 151200](https://user-images.githubusercontent.com/5914393/77545794-40921580-6eab-11ea-8098-445028b26137.png)

looking forward to a solution

**Comment by teamupdivision** [comment]
Hello

Thank you for your response.

Can you please let me know where did you take the code sample from `<div class="input-group-append"> <span class="input-group-text"> <a href=""><i class="fa fa-eye-slash" aria-hidden="true"></i></a> </span> </div>`

Thank you

**Comment by jcherrabi** [comment]
i'm not sure what do you mean by your question> th ecode is taken from the LOGIN page of the NOW UI DASHBOARD LARAVEL PRO. if you are part of Creative Tim than you should already have that... i'm sure what exactly i can do to help here apart from pointing to you the online version of this template. which can be found here: https://www.creative-tim.com/live/now-ui-dashboard-pro-laravel 
all i want to do is be able to add the eye slash to reveal the password on the right side of the password text as shown in my image above. without running to the visual issue i showed.

**Comment by dragosct** [comment]
Hi guys! Please see the image attached and the code in the right for the input group append input. 
<img width="1909" alt="Screenshot 2020-04-08 at 11 37 16" src="https://user-images.githubusercontent.com/17456857/78763150-78aa5580-798d-11ea-8a64-242df578c472.png">


Regards,
Dragos
