### ISSUE TITLE
Documentation doesn't load js files

### ISSUE THREAD

**Issue by oliverhermanni** [creativetimofficial/ct-now-ui-dashboard-pro-laravel#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Documentation shows examples for the different plugins,

# Current Behavior

None of the plugin examples work.

# Failure Information (for bugs)

Checking the developer console in my browser shows, that all JS files produce a 404 error.

## Steps to Reproduce

Load the documentation from your server. Check developer console for 404 errors or eg. go to jQuery Tagsinput page to see, that it does not work. Neither do the rest.

## Context

* Desktop PC
* Windows 10
* Latest Chrome

## Failure Logs

Please include any relevant log snippets or files here.

![image](https://user-images.githubusercontent.com/1240179/103510126-dd370a00-4e64-11eb-8e34-09bb84e8f015.png)

**Comment by teamupdivision** [comment]
Hello @oliverhermanni.

Thank you for reporting this, and for using Creative Tim products.
We've made the necessary fixes and pushed the to the live demo and product archive.
If you find anymore issues please fill free to reopen this issue.

All the best

**Comment by oliverhermanni** [comment]
Hi,

thanks! Checked the docs and they seem to work fine now - except for the [tagsinput plugin](https://now-ui-dashboard-pro-laravel.creative-tim.com/docs/plugins/jquery-tagsinput.html). It's not displayed properly. The tags are there, but they are white bg on white text, it seems.

**Comment by teamupdivision** [comment]
Fixed, thank you!

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
