### ISSUE TITLE
Migration uses old id functions, therefore can't be used for foreignId()

### ISSUE THREAD

**Issue by oliverhermanni** [creativetimofficial/ct-now-ui-dashboard-pro-laravel#4]
# Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Use foreignId() to link table id's

# Current Behavior

The migration uses $table->increments('id'), which does not allow to use foreignId(). 

# Failure Information (for bugs)

Migrations in Laravel 7.x and 8.x use $table->bigIncrements() or the alias $table->id() to create an id for tables. Those are 8-byte integers. $table->increments only uses a 4-byte, which is incompatible with foreignId(). 

## Context

This might not be a bug, but a nice to have update (which probably should be fixed in the other templates also). 

For the above named functions please check Laravel 8.x docs or vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php

**Comment by teamupdivision** [comment]
Hello @oliverhermanni, thank you for using Creative Tim products.
Thank you for the recommendations.
Let us know if you have any issue with the product.

All the best

**Comment by teamupdivision** [comment]
If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
