### ISSUE TITLE
PAckage manifest error on install conform Readme

### ISSUE THREAD

**Issue by hjtempelaar** [creativetimofficial/ct-now-ui-dashboard-pro-laravel#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
Black installation after download and following the instructions in the readme file. I didn't expect errors and outdated packages

# Current Behavior
Errors of outdated packages and installation errors

What is the current behavior?

# Failure Information (for bugs)
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Package spatie/laravel-cors is abandoned, you should avoid using it. Use laravel/framework instead.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In PackageManifest.php line 131:

  Undefined index: name

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
Follow the steps in the attached readme

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Lenovo Laptop
* Operating System: Windows 10
* Browser and Version: not relevant

## Failure Logs

Please include any relevant log snippets or files here.
I bought the product an hour ago.

**Comment by teamupdivision** [comment]
Hello @hjtempelaar, thank you for using Creative Tim products.
We will revise the outdated packages.

Regarding the undefined index name issue, it's most probably a composer version problem.
You need to either update or downgrade your composer, please check this link:
https://jianjye.com/articles/30/how-to-fix-undefined-index-name-in-packagemanifestphp-line-131-error-with-composer

You should also remove the vendor folder and package-lock.json file after upgrading/downgrading composer.

All the best

**Comment by teamupdivision** [comment]
If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
