### ISSUE TITLE
Issue download de full version to freelancer lincense

### ISSUE THREAD

**Issue by fenriquez916** [creativetimofficial/ct-now-ui-dashboard-pro-laravel#7]
# Prerequisites

I bought this template and tried to download the full version.

# Expected Behavior

Download the full version to freelancer license.

# Current Behavior

I only can download the demo

# Failure Information (for bugs)

I can´t download the full version

**Comment by teamupdivision** [comment]
Hello,

Thanks for using Creative Tim products.
What exactly do you mean you can only download the demo, what happens exactly?

Thank you

**Comment by teamupdivision** [comment]
Hi @fenriquez916,

We would like to check if the issue was solved or if you can share a few more details on the steps followed. Please let us know if there is anything else we can help with and if you have any other issues.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @fenriquez916,

Hope the problem has been solved. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
